### ISSUE TITLE
Make a Kafka authorization middleware based on Casbin

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/kafka-casbin#1]
See:

1. https://github.com/Bisnode/opa-kafka-plugin
2. https://github.com/aiven/aiven-kafka-auth

**Comment by hsluoyz** [comment]
@elfisworking I saw your code at: https://github.com/elfisworking/jcasbin-kafka-plugin , can you make PR to this repo as official hosting? BTW plz also add README.

**Comment by elfisworking** [comment]
OK! i will do a pr. But now I just started the project and built the basic structure. It will take me some time to finish

**Comment by hsluoyz** [comment]
@elfisworking OK! You can refer to the two projects I give as example.

**Comment by hsluoyz** [comment]
@seriouszyx plz work on this issue as next step.
